# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos1706_v0.2.0"
  config.vm.network "public_network", bridge:"eno1", type: "dhcp"
  config.vm.provision :chef_solo do |chef|
    chef.install = false
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe "mirror"
    chef.add_recipe "httpd"
  end  
end
